### ISSUE TITLE
使用Zepto v1.1.6 后关闭不了dialog对话框

### ISSUE THREAD

**Issue by jianliulin** [progrape/weui.js#13]
$dialog = $(html);
        $('body').append($dialog);
        $dialog.on('click', '.weui_btn_dialog', function () {
            var button = options.buttons[$(this).index()];
            var cb = button.onClick || $.noop;
            cb.call();
            $.weui.closeDialog();

  提示 db.call 出错，“Uncaught TypeError: Cannot read property 'call' of undefined”

 另外有两个建议
  1.能否添加msg组件
   2.能否整合nice-validator验证插件

**Comment by progrape** [comment]
@jianliulin 感谢反馈，报错是因为 zepto 没有 `$.noop` 为 undefined，当成函数来调用了，做了兼容之后可以关闭了。

至于 `msg` 组件，这个是 UI 层面的组件，不需要 JS 功能，写上 DOM 结构就能使用了；表单验证，这里也有封装好的方法，能否满足使用？https://github.com/progrape/weui.js/wiki/form

**Comment by jianliulin** [comment]
weui.js内置的验证我已经在用，相对简单了一点，不过还是很好用，谢谢！！
