### ISSUE TITLE
tab结合router该如何初始化页面？

### ISSUE THREAD

**Issue by damichn** [progrape/weui.js#14]
使用router初始化首页为tab的应用失败，能给出这两者结合使用的例子吗

**Comment by progrape** [comment]
失败是指什么情况？

**Comment by damichn** [comment]
页面第一次加载tab的切换按钮不起作用 并且weui_tab_bd_item 的display属性没有变为block
刷新浏览器页面后就恢复正常使用了

**Comment by progrape** [comment]
好的，我排查一下，谢谢反馈~

**Comment by progrape** [comment]
@damichn 生产环境建议你使用更专业的路由，例如这里推荐的，https://github.com/sorrycc/awesome-javascript#routing

WeUI demo 里面的路由比较简陋，功能也仅仅是满足 demo 本身使用而已，目前没有太多工夫去弄完善它。

**Comment by damichn** [comment]
好的，谢谢解答。

**Comment by damichn** [comment]
1、经过半天的测试我发现并不是路由的问题。
2、我分别测试了weui.js 中的tab方法和表单验证方法后发现对于html中已经存在的dom绑定是没有问题的，而对于绑定之后使用js动态添加的dom是不起作用的，所以我怀疑是weui.js的问题，请有时间帮忙解决一下。
3、项目急用，谢谢。

**Comment by progrape** [comment]
按我的理解，这是正常的。你对一些 DOM 进行操作，需要先存在这些 DOM，后面加进来的是不会起作用的（事件委托除外）。

tab 和 表单验证实际上是进行 DOM 操作，你调用一下 `$('#tab').tab()` 方法，就是针对页面中已有的 `#tab` 元素进行操作，后面加进来的不会主动生效的，除非你对加进来的元素再进行一次操作。

**Comment by heii** [comment]
@damichn 我也碰到这个问题了，做了个临时的解决方法，在render里延时300毫秒加载，然后再return dom：`setTimeout(function(){$('.weui_tab').tab();},300);`
