### ISSUE TITLE
关于dialog的一些意见

### ISSUE THREAD

**Issue by LeeJim** [progrape/weui.js#34]
我发现你给按钮的监听事件里，先执行callback再执行关闭dialog方法。
如果在以下这种情况就会有一些问题：
如果callback又调用dialog的话，这样$dialog的值是新的对话框，然后执行关闭就把新的对话框关闭了。
效果就是：新的对话框一出现就关闭了。

建议：
因为你给fadeOut一个fast的参数，它的延时时间是200ms，因此你可以给callback一个200ms的setTimeout或者先执行closeDialog()再执行callback

**Comment by progrape** [comment]
@LeeJim 有道理，thanks~
